### ISSUE TITLE
Doesn't run on GPU

### ISSUE THREAD

**Issue by lyh7283230** [zhengziqiang/ForkGAN#2]
Nice work! Thank you for sharing your code.
When I run your code, I just find it doesn't run on GPU. What's the matter? Looking forward to your reply.

**Comment by HaoL20** [comment]
https://github.com/zhengziqiang/ForkGAN/blob/master/model.py#line362

**Comment by HaoL20** [comment]
It should be be the problem of `dataset_dir` , maybe you need to modify it here
[https://github.com/zhengziqiang/ForkGAN/blob/master/model.py#L362](model.py)

**Comment by HaoL20** [comment]
It should be be the problem of dataset_dir , maybe you need to modify here
[model.py](https://github.com/zhengziqiang/ForkGAN/blob/master/model.py#L362)

**Comment by HaoL20** [comment]
It should be be the problem of `dataset_dir` , maybe you need to modify it here
[model.py](https://github.com/zhengziqiang/ForkGAN/blob/master/model.py#L362)

**Comment by HaoL20** [comment]
It should be the problem of `dataset_dir` , maybe you need to modify it [here](https://github.com/zhengziqiang/ForkGAN/blob/master/model.py#L362)

**Comment by lyh7283230** [comment]
> It should be the problem of `dataset_dir` , maybe you need to modify it [here](https://github.com/zhengziqiang/ForkGAN/blob/master/model.py#L362)

Well, I use your default setting and my own dataset. To be specific I put my dataset in the folder of datasets. But it can't just run on GPU.
